-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Direct Connection Test by anushree.chauhan@external.danone.com *


-- ************************************** DEV_DWH.R_CUSTOMER
CREATE TABLE DEV_DWH.R_CUSTOMER
(
 SOURCE_SYSTEM varchar(12) NOT NULL,
 CUSTOMER_CODE varchar(30) NOT NULL,
 CUSTOMER_NAME varchar(105) NOT NULL,

 CONSTRAINT PK_R_SAP_CUS_BAS PRIMARY KEY ( SOURCE_SYSTEM, CUSTOMER_CODE )
)
COMMENT = 'Customer Basic Data';

-- ************************************** DEV_DWH.R_CUSTOMER_EMAIL
CREATE TABLE DEV_DWH.R_CUSTOMER_EMAIL
(
 SOURCE_SYSTEM     varchar(12) NOT NULL,
 CUSTOMER_CODE     varchar(30) NOT NULL,
 EMAIL_ADDRESS_COD varchar(30) NOT NULL,

 CONSTRAINT PK_R_CUS_EML PRIMARY KEY ( SOURCE_SYSTEM, EMAIL_ADDRESS_COD )
)
COMMENT = 'E-Mail Addresses';

-- ************************************** DEV_DWH.R_CUSTOMER_ADDRESS
CREATE TABLE DEV_DWH.R_CUSTOMER_ADDRESS
(
 SOURCE_SYSTEM varchar(12) NOT NULL,
 ADDRESS_COD   varchar(30) NOT NULL,
 CUSTOMER_CODE varchar(30) NOT NULL,
 BGN_VLD_DAT   date NOT NULL,

 CONSTRAINT PK_R_GEO_ADR PRIMARY KEY ( SOURCE_SYSTEM, ADDRESS_COD, BGN_VLD_DAT )
)
COMMENT = 'Addresses';

